server:
  port: 8989

ceph:
  accessKeyId: D6SK4TED4GDR00QKAA6H
  secretAccessKey: dGD3xrBEoDTp3k9Ux1Wa9PiQdzJovlDdUBz8NOGD

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  add-proxy-headers: false
  ignored-headers: Access-Control-Allow-Origin
  sensitiveHeaders:
  routes:
    ceph-upload:
      path: /ceph-upload/**
      url: http://192.168.40.140:7480/new-bucket-4ed036c5/
      stripPrefix: true
    ceph-download:
      path: /ceph-download/**
      url: http://192.168.40.140:7480/new-bucket-4ed036c5/
      stripPrefix: true



ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


security:
  oauth2:
    baseurl: http://localhost:8989
    resource:
      token-info-uri: ${security.oauth2.baseurl}/oauth/check_token
    client:
      accessTokenUri: ${security.oauth2.baseurl}/oauth/token
      userAuthorizationUri: ${security.oauth2.baseurl}/oauth/authorize
      clientId: client
      clientSecret: 123456
